repos:
- repo: https://github.com/myint/autoflake
  rev: v2.1.1
  hooks:
  - id: autoflake
    args:
    - "--in-place"
    - "--remove-all-unused-imports"
    - "--remove-unused-variable"
    - "--ignore-init-module-imports"
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - "--profile=black"
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
  - id: nbstripout
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/google/yamlfmt
  rev: v0.10.0
  hooks:
  - id: yamlfmt
    args: ['-formatter=indentless_arrays=true']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-yaml
    args: ["--unsafe"]
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-ast
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--ignore, "E226,E302,E41,W503,E203,N812,E501", --max-line-length, "102"]
    exclude: "tests/"
    additional_dependencies:
    - flake8-bugbear
    - flake8-simplify
    - flake8-logging
    - pep8-naming
    - flake8-newspaper-style
    - flake8-annotations-coverage
    - flake8-future-annotations
