name: Lint
on: push
jobs:
  lint:
    env:
      python-version: "3.13"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Lint with pre-commit
      run: |-
        python -m pip install --upgrade pip
        pip install "pre-commit<4"
        pre-commit run -a
